apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
spec:
  replicas: 3  # Number of pod replicastest
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: binod0506/kubernetes-ci-cd-pipelinev2:067fa8ede978ff47fc2195e25f370a93fd64fdf8

          ports:
            - containerPort: 8081