apiVersion: apps/v1
kind: Deployment

metadata:
  name: engitronix-app-deployment
  namespace: default

spec:
  replicas: 3

  selector:
    matchLabels:
      app: engitronix-app

  template:
    metadata:
      labels:
        app: engitronix-app

    spec:
      containers:
        - name: nuvora-app-container
          image: binod0506/kubernetes-ci-cd-pipelinev2:db34519e12cbd445861fe877c884c5454f0d2334
          ports:
            - containerPort: 8081