apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  selector:
    app: user-app  # This should match the label in your deployment's pod template
  ports:
    - protocol: TCP
      port: 8081  # The port the service will expose
      targetPort: 8081  # The port on the pods